CRUD_Personas/CRUD_Personas_UI_ASP/Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using CRUD_Personas_BL.Listados;
using CRUD_Personas_BL.Gestora;
using CRUD_Personas_BL.Utilidades;
using CRUD_Personas_UI_ASP.Models.ViewModels;
using CRUD_Personas_Entidades;
using CRUD_Personas_UI_ASP.Models;

namespace CRUD_Personas_UI_ASP.Controllers
{
    public class DepartamentosController : Controller
    {
        #region Actions
        //Index

        /// <summary>
        ///  Action Index que prepara una lista de departamentos. Si se produce cualquier tipo de error se prepara una view de error
        /// </summary>
        /// <returns>ActionResult action</returns>
        public ActionResult Index()
        {
            ActionResult action;
            
            try {
                action = View(ListadosBL.obtenerDepartamentos());
            }
            catch (Exception) {
                ViewBag.Mensaje = "Algo ocurrio al acceder a la base de datos o algun error extraño ocurrio.";
                action = View("ViewNotFoundDepartamentos");
            }
            return action;
        }

        //Details

        /// <summary>
        ///  Action Details que prepara un departamento con una lista de personas con nombre y apellidos. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>ActionResult action</returns>
        public ActionResult Details(int id)
        {
            ActionResult action;
            try
            {
                List<ClsPersonaNombreApellidos> personasConNombreApellidos = new List<ClsPersonaNombreApellidos>();
                List<ClsPersona> personasDeDepartamento =  ListadosBL.obtenerPersonasDeDepartamento(id);

                foreach (ClsPersona persona in personasDeDepartamento) {
                    personasConNombreApellidos.Add(new ClsPersonaNombreApellidos(persona));
                }

                ClsDepartamentoConPersonasSimplificadasVM departamentoVM = new ClsDepartamentoConPersonasSimplificadasVM
                                                                          (ListadosBL.obtenerDepartamento(id), personasConNombreApellidos);
                action = View(departamentoVM);
            }
            catch (Exception)
            {
                ViewBag.Mensaje = "Algo ocurrio al acceder a la base de datos o algun error extraño ocurrio.";
                action = View("ViewNotFoundDepartamentos");
            }
            return action;
        }

        //Create//

        /// <summary>
        /// Action Create que devuelve un ActionResult a una view Create. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Action HttpPost Create que prepara las cosas necesarias para una funcion que añadira una departamento a la BBDD. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="clsDepartamento"></param>
        /// <returns>ActionResult action</returns>
        [HttpPost]
        public ActionResult Create(ClsDepartamento clsDepartamento)
        {
            ActionResult action = View();
            try
            {
                if (ModelState.IsValid) {
                    GestoraDepartamentoBL.anhadirDepartamento(clsDepartamento);
                    action = RedirectToAction("Index");
                }
            }
            catch(Exception)
            {
                ViewBag.Mensaje = "Algo ocurrio al acceder a la base de datos o algun error extraño ocurrio.";
                action = View("ViewNotFoundDepartamentos");

            }
            return action;
        }

        /// <summary>
        /// Action Edit que prepara un departamento concreto. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>ActionResult action</returns>
        public ActionResult Edit(int id)
        {
            ActionResult action;
            try
            {
                ClsDepartamento departamento = ListadosBL.obtenerDepartamento(id);
                action = View(departamento);
            }
            catch (Exception)
            {
                ViewBag.Mensaje = "Algo ocurrio al acceder a la base de datos o algun error extraño ocurrio.";
                action = View("ViewNotFoundDepartamentos");
            }
            return action;
        }

        /// <summary>
        ///  Action HttpPost Edit que prepara las cosas necesarias para una funcion que actualizara un departamento a la BBDD. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="clsDepartamento"></param>
        /// <returns>ActionResult action</returns>
        [HttpPost]
        public ActionResult Edit(ClsDepartamento clsDepartamento)
        {
            ActionResult action;
            try
            {
                if (ModelState.IsValid)
                {
                    int numActualizaciones = GestoraDepartamentoBL.editarDepartamento(clsDepartamento);
                    ViewBag.NumCambios = numActualizaciones;
                    action = View("ViewExitoDepartamentos");
                }
                else {
                    ClsDepartamento departamento = ListadosBL.obtenerDepartamento(clsDepartamento.ID);
                    action = View(departamento);
                }
            }
            catch(Exception)
            {
                ViewBag.Mensaje = "Algo ocurrio al acceder a la base de datos o algun error extraño ocurrio.";
                action = View("ViewNotFoundDepartamentos");
            }
            return action;
        }

        /// <summary>
        /// Action Delete que prepara un departamento en concreto. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>ActionResult action</returns>
        public ActionResult Delete(int id)
        {
            ActionResult action;
            try {
                ClsDepartamento departamento = ListadosBL.obtenerDepartamento(id);
                action = View(departamento); 
            }
            catch (Exception) {
                ViewBag.Mensaje = "Algo ocurrio al acceder a la base de datos o algun error extraño ocurrio.";
                action = View("ViewNotFoundDepartamentos");
            }
            return View();
        }

        /// <summary>
        /// Action HttpPost DeletePost que prepara las cosas necesarias para una funcion que eliminara un departamento a la BBDD. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>ActionResult action</returns>
        [HttpPost, ActionName("Delete")]
        public ActionResult DeletePost(int id)
        {
            ActionResult action;
            try
            {
                if (UtilidadesBL.comprobarDepartamentoTienePersonas(id)) //Si el departamento tiene asociadas personas
                {
                    ViewBag.Mensaje = "El departamento contiene personas, no se pudo eliminar.";
                    action = View("ViewNotFoundDepartamentos");
                }
                else {
                    int numEliminaciones = GestoraDepartamentoBL.eliminarDepartamento(id);
                    ViewBag.NumCambios = numEliminaciones;
                    action = View("ViewExitoDepartamentos");
                }
            }
            catch(Exception)
            {
                ViewBag.Mensaje = "Algo ocurrio al acceder a la base de datos o algun error extraño ocurrio.";
                action = View("ViewNotFoundDepartamentos");
            }
            return action;
        }
        #endregion
    }
}

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Departamentos/Create.cshtml
@model CRUD_Personas_Entidades.ClsDepartamento

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Create Departamento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" required class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Departamentos/Delete.cshtml
@model CRUD_Personas_Entidades.ClsDepartamento

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delete Departamento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Departamentos/Details.cshtml
@model CRUD_Personas_UI_ASP.Models.ViewModels.ClsDepartamentoConPersonasSimplificadasVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

    <div>
        <h1>Details Departamento</h1>
        
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.Nombre)</strong> @Html.DisplayFor(model => model.Nombre)
            </dt>
            <strong>@Html.DisplayNameFor(model => model.ListaPersonas)</strong>
            @{
                if (Model.ListaPersonas.Count > 0) //Si el departamento tiene asignado alguna persona
                {
                    <ul>
                        @foreach (ClsPersonaNombreApellidos persona in Model.ListaPersonas)
                        {
                            <li>@persona.Nombre  @persona.Apellidos</li>
                        }
                    </ul>
                }
                else
                {
                    <p>No hay personas asignadas a este departamento</p>
                }
            }
        </dl>
    </div>
    <div>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        <a asp-action="Index">Back to List</a>
    </div>
</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Departamentos/Edit.cshtml
@model CRUD_Personas_Entidades.ClsDepartamento

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

    <h4>Edit Departamento</h4>
    <h3>Edite los campos del departamento</h3>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" required class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Departamentos/Index.cshtml
@model IEnumerable<CRUD_Personas_Entidades.ClsDepartamento>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h1>Gestión Departamentos</h1>
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table" border="1">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    @Html.ActionLink("Inicio","Index","Home")
</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Departamentos/ViewExitoDepartamentos.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ViewExitoDepartamentos</title>
</head>
<body>

    <h1>Gestión Departamentos</h1>
    <h2 style="color:green">Cambios realiazados con exito!!</h2>
    Detalles de los cambios realizados: Numero de modificaciones realizadas: @ViewBag.NumCambios
    <br />
    @Html.ActionLink("Inicio Departamentos", "Index", "Departamentos")
</body>

</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Departamentos/ViewNotFoundDepartamentos.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ViewNotFoundDepartamentos</title>
</head>
<body>
    <h1>Gestión Departamentos</h1>
    <h2 style="color:red">404.Error. Algo salio mal!</h2>
    Detalles del error: @ViewBag.Mensaje
    <br />
    @Html.ActionLink("Inicio Departamentos", "Index", "Departamentos")
</body>

</html>