CRUD_Personas/CRUD_Personas_UI_ASP/Controllers/API/PersonasController.cs
using CRUD_Personas_BL.Listados;
using CRUD_Personas_BL.Gestora;
using CRUD_Personas_Entidades;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Net;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CRUD_Personas_UI_ASP.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class PersonasController : ControllerBase
    {
        // GET: api/<PersonasController> ruta para acceder a la api con localHost/...
        [HttpGet]
        public IEnumerable<ClsPersona> Get()
        {
            List<ClsPersona> listaPersonas = new List<ClsPersona>();
            try
            {
                listaPersonas = ListadosBL.obtenerPersonas();
            }
            catch (Exception)
            {

            }
            return listaPersonas;
        }
        // GET api/<PersonasController>/5
        //Documentar la ruta que tiene cada parte 
        [HttpGet("{id}")]
        public ClsPersona Get(int id) //
        {
            ClsPersona persona = new ClsPersona();
            try
            {
                persona = ListadosBL.obtenerPersona(id);
            }
            catch (Exception)
            {

            }
            return persona;
        }

        // POST api/<PersonasController>
        [HttpPost]
        public void Post([FromBody] ClsPersona persona) //Para crear recuros
        {
            try
            {
                GestoraPersonasBL.anhadirPersona(persona);
            }
            catch (Exception)
            {

            }
        }

        // PUT api/<PersonasController>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] ClsPersona persona) //Para editar recursos
        {
            try
            {
                GestoraPersonasBL.editarPersona(persona);
            }
            catch (Exception)
            {

            }
        }

        // DELETE api/<PersonasController>/5
        [HttpDelete("{id}")]
        public HttpStatusCode Delete(int id) //Eliminar Recursos
        {
            HttpStatusCode httpStatusCode = HttpStatusCode.Created;
            try
            {
                if (GestoraPersonasBL.eliminarPersona(id) == 0)
                {
                    httpStatusCode = HttpStatusCode.Created;
                }
            }
            catch (Exception)
            {
                httpStatusCode = HttpStatusCode.ServiceUnavailable;
            }

            return httpStatusCode;
        }
    }
}

CRUD_Personas/CRUD_Personas_UI_ASP/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using CRUD_Personas_UI_ASP.Models;
using CRUD_Personas_UI_ASP.Models.ViewModels;
using CRUD_Personas_BL.Listados;
using CRUD_Personas_Entidades;
using CRUD_Personas_BL.Gestora;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Linq;

namespace CRUD_Personas_UI_ASP.Controllers
{
    public class PersonasController : Controller
    {

        private readonly string mensajeError = "Algo ocurrio al acceder a la base de datos o algun error extraño ocurrio.";
        #region Actions
        //Index

        /// <summary>
        ///  Action Index que prepara una lista de personas simplificadas(Nombre, Apellidos) con nombre de departamento. Si se produce cualquier tipo de error se prepara una view de error
        /// </summary>
        /// <returns>IActionResult action</returns>
        public IActionResult Index()
        {
            IActionResult action;
            List<ClsPersonaSimplificadaNombreDepartamento> listaClsPersonaSimplificada = new List<ClsPersonaSimplificadaNombreDepartamento>();
            try
            {
                List<ClsPersona> listaPersonas = ListadosBL.obtenerPersonas();
                List<ClsDepartamento> listaDepartamentos = ListadosBL.obtenerDepartamentos();
                ClsPersona persona;
                for (int i = 0; i < listaPersonas.Count; i++)
                {
                    persona = listaPersonas.ElementAt(i);

                    listaClsPersonaSimplificada.Add(new ClsPersonaSimplificadaNombreDepartamento(persona,
                                                    obtenerNombreDepartamento(listaDepartamentos, persona.IdDepartamento)));
                }
                action = View(listaClsPersonaSimplificada);
            }
            catch (Exception)
            {
                ViewBag.Mensaje = mensajeError;
                action = View("ViewNotFoundPersonas");
            }
            return action;
        }

        //Details

        /// <summary>
        ///  Action Details que prepara una persona con nombre de departamento. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>IActionResult action</returns>
        public IActionResult Details(int id)
        {
            IActionResult action;
            try
            {
                ClsPersonaNombreDepartamento clsPersonaDepartamento;
                ClsPersona clsPersona = ListadosBL.obtenerPersona(id);

                clsPersonaDepartamento = new ClsPersonaNombreDepartamento(clsPersona, ListadosBL.obtenerNombreDepartamento(clsPersona.IdDepartamento));
                action = View(clsPersonaDepartamento); 
            }
            catch (Exception)
            {
                ViewBag.Mensaje = mensajeError;
                action = View("ViewNotFoundPersonas");
            }

            return action;
        }

        //Create//

        /// <summary>
        /// Action Create que prepara una persona con lista de departamentos. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <returns>IActionResult action</returns>
        public IActionResult Create()
        {
            IActionResult action;
           
            try
            {
                ClsPersonaListaDepartamentosVM clsPersonaDepartamentos = new ClsPersonaListaDepartamentosVM();
                clsPersonaDepartamentos.ListaDepartamentos = ListadosBL.obtenerDepartamentos();
                action = View(clsPersonaDepartamentos);
            }
            catch (Exception)
            {
                ViewBag.Mensaje = mensajeError;
                action = View("ViewNotFoundPersonas");
            }
            return action;
        }

        /// <summary>
        /// Action HttpPost Create que prepara las cosas necesarias para una funcion que añadira una persona a la BBDD. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="clsPersonaDepartamento"></param>
        /// <param name="imagen"></param>
        /// <returns>IActionResult action</returns>
        [HttpPost]
        public IActionResult Create(ClsPersonaListaDepartamentosVM clsPersonaDepartamento, IFormFile imagen)
        {
            IActionResult action = null;
            try
            {
                if (ModelState.IsValid) {
                    if (imagen != null)
                    {
                        clsPersonaDepartamento.Foto = rellenarArrayByte(imagen);
                    }
                    GestoraPersonasBL.anhadirPersona(clsPersonaDepartamento);
                    action = RedirectToAction("Index");
                }
                else {
                    ClsPersonaListaDepartamentosVM clsPersonaDepartamentos = new ClsPersonaListaDepartamentosVM();
                    clsPersonaDepartamentos.ListaDepartamentos = ListadosBL.obtenerDepartamentos();
                    action = View("Create", clsPersonaDepartamentos);
                }
            }
            catch (Exception)
            {
                ViewBag.Mensaje = "Algo ocurrio al intentar guardar la persona nueva en la base de datos.";
                action = View("ViewNotFoundPersonas");
            }
            return action;
        }

        //Edit

        /// <summary>
        /// Action Edit que prepara una persona con lista de departamentos. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>IActionResult action</returns>
        public IActionResult Edit(int id)
        {
            IActionResult action;
            try
            {
               ClsPersonaListaDepartamentosVM clsPersonaDepartamentos = new ClsPersonaListaDepartamentosVM(ListadosBL.obtenerPersona(id),
                                                                                                           ListadosBL.obtenerDepartamentos());
                action = View(clsPersonaDepartamentos);
            }
            catch (Exception)
            {
                ViewBag.Mensaje = mensajeError;
                action = View("ViewNotFoundPersonas");
            }
            return action;
        }

        /// <summary>
        /// Action HttpPost Edit que prepara las cosas necesarias para una funcion que actualizara una persona a la BBDD. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="clsPersonaDepartamento"></param>
        /// <param name="imagen"></param>
        /// <returns>IActionResult action</returns>
        [HttpPost]
        public IActionResult Edit(ClsPersona clsPersona, IFormFile imagen)
        {
            IActionResult action;
            int numActualizaciones;
            try
            {
                if (ModelState.IsValid)
                {
                    if (imagen != null) //Si el usuario a ingresado una imagen
                    {
                        clsPersona.Foto = rellenarArrayByte(imagen);
                    }
                    numActualizaciones = GestoraPersonasBL.editarPersona(clsPersona);
                    ViewBag.NumCambios = numActualizaciones;
                    action = View("ViewExitoPersonas");
                }
                else {
                    //Hay que hacerlo con View y no con RedirectToAction("Edit"), por que con RedirectToAction no salen los mensajes de validacion(Ej: Campo obligatorio)
                    action = View("Edit",new ClsPersonaListaDepartamentosVM(clsPersona, ListadosBL.obtenerDepartamentos()));
                }
            }
            catch (Exception)
            {
                ViewBag.Mensaje = "Algo ocurrio al intentar actualizar la persona en la base de datos.";
                action = View("ViewNotFoundPersonas");
            }
            return action;
        }

        //Delete

        /// <summary>
        /// Action Delete que prepara una persona con nombre de departamento. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>IActionResult action</returns>
        public IActionResult Delete(int id)
        {
            IActionResult action;
            try
            {
                ClsPersona clsPersona = ListadosBL.obtenerPersona(id);
                ClsPersonaNombreDepartamento clsPersonaConDepartamento;
                clsPersonaConDepartamento = new ClsPersonaNombreDepartamento(clsPersona, ListadosBL.obtenerNombreDepartamento(clsPersona.IdDepartamento));
                action = View(clsPersonaConDepartamento);
            }
            catch (Exception)
            {
                ViewBag.Mensaje = mensajeError;
                action = View("ViewNotFoundPersonas");
            }

            return action;
        }

        /// <summary>
        /// Action HttpPost DeletePost que prepara las cosas necesarias para una funcion que eliminara una persona a la BBDD. Si se produce cualquier tipo de error se prepara una view de error.
        /// </summary>
        /// <param name="id"></param>
        /// <returns>IActionResult action</returns>
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int id)
        {
            IActionResult action;
            try {
                int numEliminaciones = GestoraPersonasBL.eliminarPersona(id);
                ViewBag.NumCambios = numEliminaciones;
                action = View("ViewExitoPersonas");
            }
            catch (Exception) {
                ViewBag.Mensaje = "Algo ocurrio al intentar eliminar la persona en la base de datos.";
                action = View("ViewNotFoundPersonas");
            }

            return action;
        }
        #endregion


        #region Metodos Privados

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Personas/Create.cshtml
@model CRUD_Personas_UI_ASP.Models.ViewModels.ClsPersonaListaDepartamentosVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <h1>Create Persona</h1>
    <h3>Rellene los campos para crear una persona nueva</h3>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" required class="form-control" />
                    @Html.ValidationMessageFor(model => model.Nombre)
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Apellidos" class="control-label"></label>
                    <input asp-for="Apellidos" required class="form-control" />
                    @Html.ValidationMessageFor(model => model.Apellidos)

                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Telefono" class="control-label"></label>
                    <input asp-for="Telefono" required class="form-control" />
                    @Html.ValidationMessageFor(model => model.Telefono)
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Direccion" class="control-label"></label>
                    <input asp-for="Direccion" required class="form-control" />
                    @Html.ValidationMessageFor(model => model.Direccion)

                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Foto" class="control-label"></label>
                    <input type="file" name="imagen" class="form-control" asp-for="Foto" accept=".png, .jpg">
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="FechaNacimiento" class="control-label"></label>
                    <input type="date" value="@Model.FechaNacimiento.ToString("yyyy-MM-dd")" asp-for="FechaNacimiento" class="form-control" />
                </div>
                <br />
                <div class="form-group">
                    <select name="IdDepartamento">
                        @{
                            foreach (CRUD_Personas_Entidades.ClsDepartamento departamento in Model.ListaDepartamentos)
                            {
                                <option value="@departamento.ID">@departamento.Nombre</option>
                            }
                        }
                    </select>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Personas/Delete.cshtml
@model CRUD_Personas_UI_ASP.Models.ClsPersonaNombreDepartamento

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h1>Delete Persona</h1>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        @{
            var base64 = Convert.ToBase64String(Model.Foto);
            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

            <img src="@imgSrc" width="80" height="80" />
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NombreDepartamento)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NombreDepartamento)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Personas/Details.cshtml
@model CRUD_Personas_UI_ASP.Models.ClsPersonaNombreDepartamento

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h1>Details Persona</h1>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.Nombre)</strong> @Html.DisplayFor(model => model.Nombre)
            </dt>
            <dd><br /></dd>
            <dt class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.Apellidos)</strong> @Html.DisplayFor(model => model.Apellidos)
            </dt>
            <dd><br /></dd>
            <dt class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.Telefono)</strong> @Html.DisplayFor(model => model.Telefono)
            </dt>
            <dd><br /></dd>
            <dt class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.Direccion)</strong> @Html.DisplayFor(model => model.Direccion)
            </dt>
            <dd><br /></dd>
            @{
                var base64 = Convert.ToBase64String(Model.Foto);
                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                <dt class="col-sm-2">
                    <strong>@Html.DisplayNameFor(model => model.Foto)</strong>
                </dt>
                <img src="@imgSrc" wight width="80" height="80" />
            }
            <dd><br /></dd>
            <dt class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.FechaNacimiento)</strong>  @Model.FechaNacimiento.ToString("dd-MM-yyyy")
            </dt>
            <dd><br /></dd>
            <dt class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.NombreDepartamento)</strong> @Html.DisplayFor(model => model.NombreDepartamento)
            </dt>
        </dl>
    </div>
    <br />
    <div>
        <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>
</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Personas/Edit.cshtml
@model CRUD_Personas_UI_ASP.Models.ViewModels.ClsPersonaListaDepartamentosVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <h1>Edit Persona</h1>
    <h3>Edite los campos de la persona</h3>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Nombre" class="control-label"></label>
                    <input asp-for="Nombre" required class="form-control" />
                    @Html.ValidationMessageFor(model => model.Nombre)
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Apellidos" class="control-label"></label>
                    <input asp-for="Apellidos" required class="form-control" />
                    @Html.ValidationMessageFor(model => model.Apellidos)
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Telefono" class="control-label"></label>
                    <input asp-for="Telefono" required class="form-control" />
                    @Html.ValidationMessageFor(model => model.Telefono)
                </div>
                <br />
                <div class="form-group">
                    <label asp-for="Direccion" class="control-label"></label>
                    <input asp-for="Direccion" required class="form-control" />
                    @Html.ValidationMessageFor(model => model.Direccion)
                </div>
                <br />
                <!--Foto-->
                @{
                    var base64 = Convert.ToBase64String(Model.Foto);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

                    <div class="form-group">
                        <label asp-for="Foto" class="control-label"></label>
                        <img src="@imgSrc" width="80" height="80" />
                        <input type="file" name="imagen" class="form-control" accept=".png, .jpg">
                        <input hidden name="Foto" value="@base64"/>
                    </div>
                }
                <br />
                <!--FechaNacimiento-->
                <div class="form-group">
                    <label asp-for="FechaNacimiento" class="control-label"></label>
                    <input type="date" value="@Model.FechaNacimiento.ToString("yyyy-MM-dd")" asp-for="FechaNacimiento" class="form-control" />
                </div>
                <br />
                <!--Desplegable Lista Departamentos-->
                <div class="form-group">
                    <select name="IdDepartamento">

                        @{
                            foreach (CRUD_Personas_Entidades.ClsDepartamento departamento in Model.ListaDepartamentos)
                            {
                                if (departamento.ID == Model.IdDepartamento)
                                {
                                    <option value="@departamento.ID" selected="selected">@departamento.Nombre</option>
                                }
                                else
                                {
                                    <option value="@departamento.ID">@departamento.Nombre</option>
                                }
                            }
                        }
                    </select>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Personas/Index.cshtml
@model IEnumerable<CRUD_Personas_UI_ASP.Models.ClsPersonaSimplificadaNombreDepartamento>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h1>Gestión Personas</h1>
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table" border="1">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Apellidos)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NombreDepartamento)
                </th>
            </tr>

        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Apellidos)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NombreDepartamento)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <br />
    @Html.ActionLink("Inicio", "Index", "Home")
</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Personas/ViewExitoPersonas.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ViewExitoPersonas</title>
</head>
<body>
    <h1>Gestión Personas</h1>
    <h2 style="color:green">Cambios realiazados con exito!!</h2>
    Detalles de los cambios realizados: Numero de campos modificados @ViewBag.NumCambios
    <br />
    @Html.ActionLink("Inicio Personas", "Index", "Personas")
</body>
</html>

CRUD_Personas/CRUD_Personas_UI_ASP/Views/Personas/ViewNotFoundPersonas.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ViewNotFoundPersonas</title>
</head>
<body>
    <h1>Gestión Personas</h1>
    <h2 style="color:red">404.Error. Algo salio mal!</h2>
    Detalles del error: @ViewBag.Mensaje
    <br/>
    @Html.ActionLink("Inicio Personas", "Index", "Personas")
</body>
</html>